#!/usr/bin/env python3
"""Golden-file regression checks for the fixed stack-highlights toolchain.

`python tests/run_golden.py --update` deliberately refreshes expected files.
Normal mode compares generated bytes against checked-in goldens and prints a
unified diff on failure.

Every case also checks, from the run's own coverage line
("N mark(s), M placed in notes"), that
  * the number of highlights found and placed is exactly what the case expects, and
  * the "Check in book" list holds exactly the N - M highlights that were not placed
    (and is absent when everything was placed).
So a change that silently drops a highlight fails here even if someone
refreshes the goldens with --update.

Goldens whose name ends in _KNOWN_ISSUE record today's behaviour for a known
problem (see golden/README.md). They are expected to change -- deliberately --
when that problem is fixed.
"""
from __future__ import annotations
import argparse, difflib, json, re, subprocess, sys
from pathlib import Path

TESTS=Path(__file__).resolve().parent
ROOT=TESTS.parent
FIX=TESTS/'fixtures'
GOLD=TESTS/'golden'
TMP=TESTS/'.tmp'
SCRIPT=ROOT/'stack-highlights'

#  name                          fixture               fmt     extra flags                                  (found, placed)
CASES=[
    ('prose_default',            'prose_list.pdf',     'md',   [],                                           (4, 4)),
    ('prose_exact_flat',         'prose_list.pdf',     'md',   ['--context','highlight','--no-headings','--no-leadins','--no-group-lists','--no-tables'], (4, 4)),
    ('prose_dehyphenate',        'prose_list.pdf',     'md',   ['--dehyphenate'],                            (4, 4)),
    ('prose_json',               'prose_list.pdf',     'json', [],                                           (4, 4)),
    ('legal_default',            'legal_clause.pdf',   'md',   [],                                           (3, 3)),
    ('legal_clause',             'legal_clause.pdf',   'md',   ['--context','clause'],                       (3, 3)),
    ('legal_json',               'legal_clause.pdf',   'json', [],                                           (3, 3)),
    # a paragraph split across a page break; running headers; printed page numbers
    ('pagebreak_default',        'page_break.pdf',     'md',   [],                                           (4, 4)),
    ('pagebreak_json_KNOWN_ISSUE', 'page_break.pdf',   'json', [],                                           (4, 4)),
    ('pagebreak_gap_KNOWN_ISSUE', 'page_break.pdf',    'md',   ['--pages','1,3'],                            (2, 2)),
    ('pagebreak_gap_nojoin',     'page_break.pdf',     'md',   ['--pages','1,3','--no-join-pages'],          (2, 2)),
    # highlights across a line-break hyphen
    ('hyphen_default',           'hyphen_break.pdf',   'md',   [],                                           (2, 2)),
    ('hyphen_dehyphenate',       'hyphen_break.pdf',   'md',   ['--dehyphenate'],                            (2, 2)),
    ('hyphen_exact',             'hyphen_break.pdf',   'md',   ['--context','highlight','--snap','char'],    (2, 2)),
    # a small table and a footnote
    ('table_default',            'table_footnote.pdf', 'md',   [],                                           (4, 4)),
    ('table_no_tables',          'table_footnote.pdf', 'md',   ['--no-tables'],                              (4, 4)),
    ('table_footnote_section',   'table_footnote.pdf', 'md',   ['--footnotes','section'],                    (4, 4)),
    ('table_json',               'table_footnote.pdf', 'json', [],                                           (4, 4)),
    # real legal typesetting: bold run-in titles ending ".\u2014", STATE AMENDMENT block
    ('legal_emdash_default',     'legal_emdash.pdf',   'md',   [],                                           (4, 4)),
    ('legal_emdash_clause',      'legal_emdash.pdf',   'md',   ['--context','clause'],                       (4, 4)),
    ('legal_emdash_json',        'legal_emdash.pdf',   'json', [],                                           (4, 4)),
    # highlights that cannot be placed -> "Check in book"
    ('misses_default',           'misses.pdf',         'md',   [],                                           (3, 1)),
    ('misses_text',              'misses.pdf',         'txt',  [],                                           (3, 1)),
    ('misses_json',              'misses.pdf',         'json', [],                                           (3, 1)),
    ('misses_snap_char',         'misses.pdf',         'md',   ['--snap','char'],                            (3, 2)),
]
COVERAGE_RE=re.compile(r'(\d+) mark\(s\)[^\n]*?, (\d+) placed in notes')

def run_case(name,pdf,fmt,args):
    TMP.mkdir(exist_ok=True); out=TMP/f'{name}.{fmt}'
    if out.exists(): out.unlink()
    cmd=[str(SCRIPT),str(FIX/pdf),'--format',fmt,'--out',str(out),'--no-progress']+args
    cp=subprocess.run(cmd,cwd=ROOT,stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True)
    if cp.returncode or not out.exists():
        print(f'ERROR {name}: command failed\n{cp.stderr}',file=sys.stderr); return None, cp.stderr
    return out.read_bytes(), cp.stderr

def check_list_count(fmt, data: bytes):
    """How many highlights the output's "Check in book" list names (None = no list)."""
    text=data.decode('utf-8')
    if fmt=='json':
        items=json.loads(text).get('check_in_book')
        return None if items is None else len(items)
    head=re.search(r'^#+ Check in book$' if fmt=='md' else r'^=== Check in book ===$', text, re.M)
    if not head: return None
    rest=text[head.end():].splitlines()
    if fmt=='md': return sum(1 for l in rest if l.startswith('- '))
    return sum(1 for l in rest if l.startswith('p. '))

def coverage_problems(name,fmt,stderr,data,expected):
    m=COVERAGE_RE.search(stderr or '')
    if not m: return [f'{name}: no coverage line in the output']
    found,placed=int(m.group(1)),int(m.group(2)); problems=[]
    if (found,placed)!=expected:
        problems.append(f'{name}: coverage is {found} found / {placed} placed, expected {expected[0]} / {expected[1]}')
    listed=check_list_count(fmt,data)
    if found==placed and listed is not None:
        problems.append(f'{name}: everything was placed but a "Check in book" list was added')
    if found!=placed and listed!=found-placed:
        n=found-placed
        problems.append(f'{name}: "Check in book" lists {listed or 0} highlight(s), the coverage line says {n} {"is" if n==1 else "are"} missing')
    return problems

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--update',action='store_true'); ns=ap.parse_args()
    missing=sorted({pdf for _,pdf,*_ in CASES if not (FIX/pdf).exists()})
    if missing:
        print('Missing fixtures '+', '.join(missing)+'. Run: python tests/build_fixtures.py',file=sys.stderr); return 2
    GOLD.mkdir(exist_ok=True); TMP.mkdir(exist_ok=True)
    failed=0
    for name,pdf,fmt,args,expected in CASES:
        got,stderr=run_case(name,pdf,fmt,args)
        if got is None: failed+=1; continue
        problems=coverage_problems(name,fmt,stderr,got,expected)
        for p in problems: print(f'FAIL {p}',file=sys.stderr)
        exp=GOLD/f'{name}.{fmt}'
        if ns.update:
            exp.write_bytes(got); print(f'updated {exp.relative_to(ROOT)}')
            failed+=bool(problems); continue
        if not exp.exists():
            print(f'MISSING GOLDEN: {exp.relative_to(ROOT)}',file=sys.stderr); failed+=1; continue
        want=exp.read_bytes()
        if got!=want:
            print(f'FAIL {name}',file=sys.stderr)
            a=want.decode('utf-8',errors='replace').splitlines(True)
            b=got.decode('utf-8',errors='replace').splitlines(True)
            sys.stderr.writelines(difflib.unified_diff(a,b,fromfile=f'golden/{exp.name}',tofile=f'actual/{exp.name}'))
            failed+=1
        elif problems:
            failed+=1
        else:
            print(f'PASS {name}')
    if ns.update:
        print(f'Updated {len(CASES)} golden files. Review changes deliberately.')
        return 1 if failed else 0
    print(f'{len(CASES)-failed}/{len(CASES)} golden cases passed')
    return 1 if failed else 0

if __name__=='__main__': raise SystemExit(main())
