"""Generate TgIcons.kt: the desktop interface's line icons (tgdrive/web/js/core.js, ICON) as Compose
vectors, so the Android app draws exactly the same pictures. Run from tgdrive/android:

    python3 tools/gen_icons.py
"""
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
CORE = HERE.parent.parent / "web" / "js" / "core.js"
OUT = HERE.parent / "app/src/main/java/app/tgdrive/ui/theme/TgIcons.kt"

src = CORE.read_text()
block = src[src.index("export const ICON = {"):src.index("};", src.index("export const ICON = {"))]
entries = re.findall(r"^  (\w+): '(.*)',?$", block, re.M)
ATTR = re.compile(r'([\w-]+)="([^"]*)"')


def num(v):
    return float(v)


def fmt(x):
    return ("%.3f" % x).rstrip("0").rstrip(".")


def to_path(tag, a):
    if tag == "path":
        return a["d"]
    if tag == "rect":
        x, y, w, h = (num(a.get(k, 0)) for k in ("x", "y", "width", "height"))
        rx = num(a.get("rx", a.get("ry", 0)))
        ry = num(a.get("ry", a.get("rx", 0)))
        rx, ry = min(rx, w / 2), min(ry, h / 2)
        if not rx:
            return f"M{fmt(x)} {fmt(y)}h{fmt(w)}v{fmt(h)}h{fmt(-w)}z"
        return (f"M{fmt(x + rx)} {fmt(y)}h{fmt(w - 2 * rx)}a{fmt(rx)} {fmt(ry)} 0 0 1 {fmt(rx)} {fmt(ry)}"
                f"v{fmt(h - 2 * ry)}a{fmt(rx)} {fmt(ry)} 0 0 1 {fmt(-rx)} {fmt(ry)}h{fmt(-(w - 2 * rx))}"
                f"a{fmt(rx)} {fmt(ry)} 0 0 1 {fmt(-rx)} {fmt(-ry)}v{fmt(-(h - 2 * ry))}a{fmt(rx)} {fmt(ry)} 0 0 1 {fmt(rx)} {fmt(-ry)}z")
    if tag in ("circle", "ellipse"):
        cx, cy = num(a.get("cx", 0)), num(a.get("cy", 0))
        rx = num(a.get("r", a.get("rx", 0)))
        ry = num(a.get("r", a.get("ry", 0)))
        return (f"M{fmt(cx - rx)} {fmt(cy)}a{fmt(rx)} {fmt(ry)} 0 1 0 {fmt(2 * rx)} 0"
                f"a{fmt(rx)} {fmt(ry)} 0 1 0 {fmt(-2 * rx)} 0z")
    if tag == "line":
        return f"M{a['x1']} {a['y1']}L{a['x2']} {a['y2']}"
    if tag in ("polyline", "polygon"):
        pts = a["points"].replace(",", " ").split()
        d = "M" + " L".join(f"{pts[i]} {pts[i + 1]}" for i in range(0, len(pts), 2))
        return d + ("z" if tag == "polygon" else "")
    raise ValueError(tag)


lines = []
for name, svg in entries:
    parts = []
    for tag, attrs in re.findall(r"<(\w+)([^>]*)/?>", svg):
        a = dict(ATTR.findall(attrs))
        filled = a.get("fill") == "currentColor"
        width = a.get("stroke-width")
        parts.append((to_path(tag, a), filled, width))
    body = ", ".join(
        f'P("{d}"{", fill = true" if f else ""}{f", width = {w}f" if w else ""})' for d, f, w in parts)
    lines.append(f"    val {name} = TgIcon(\"{name}\", listOf({body}))")

aliases = {"image": "photo"}
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(
    "// Generated by tools/gen_icons.py from tgdrive/web/js/core.js (ICON). Do not edit by hand.\n"
    "package app.tgdrive.ui.theme\n\n"
    "@Suppress(\"unused\", \"MaxLineLength\")\n"
    "object TgIcons {\n" + "\n".join(lines) + "\n" +
    "".join(f"    val {k} = {v}\n" for k, v in aliases.items()) + "}\n")
print(f"{len(entries)} icons -> {OUT}")
